commit repository changes on 2024-08-07 [skip ci]

diff --git a/kiddin9/master/luci-app-packagesync/root/etc/init.d/packagesync b/kiddin9/master/luci-app-packagesync/root/etc/init.d/packagesync
--- a/kiddin9/master/luci-app-packagesync/root/etc/init.d/packagesync
+++ b/kiddin9/master/luci-app-packagesync/root/etc/init.d/packagesync
@@ -1,5 +1,5 @@
 #!/bin/bash /etc/rc.common
-# Copyright (C) 2023 muink
+# Copyright (C) 2023-2024 muink
 
 . "${IPKG_INSTROOT}/lib/functions.sh"
 . "${IPKG_INSTROOT}/usr/share/libubox/jshn.sh"
@@ -16,7 +16,7 @@ EXTRA_HELP=\
 	cleanup [autorm]	Clean up invalid versions"
 
 CONFIG_NAME='packagesync'
-TYPEDSECTION='packagesync'
+SCONFIG='config'
 RELEASE='release'
 
 MNTPKGS='/mnt/packagesync'
@@ -30,20 +30,46 @@ TARGETS_LIST="/var/packagesync/targetslist"
 PKGARCHS_LIST="/var/packagesync/pkgarchslist"
 RESULTPATH='/var/packagesync/results'
 # url path
-OPENWRT_URL="https://downloads.openwrt.org"
+DOWNLOAD_URL="https://downloads.openwrt.org"
 URLHREF_RELEASES='releases'
 URLHREF_SNAPSHOTS='snapshots'
 URLHREF_PACKAGES_PREFIX='packages-' # packages-22.03
 URLHREF_VERS_PACKAGES='packages'
 URLHREF_VERS_TARGETS='targets'
 
-if [ "$(uci -q get $CONFIG_NAME.@$TYPEDSECTION[0].proxy_enabled)" == "1" ]; then
-    export ALL_PROXY=$(uci -q get $CONFIG_NAME.@$TYPEDSECTION[0].proxy_protocol)://$(uci -q get $CONFIG_NAME.@$TYPEDSECTION[0].proxy_server)
-fi
-
 config_load $CONFIG_NAME
 
 
+
+# define global var: GLOBAL_*
+define_global() {
+	[ "$2" == "0" ] || { >&2 echo "$(basename $0): section $1 validation failed"; return 1; }
+
+	local error=0
+	local v ucivv="download_url rsync_url home_url bwlimit proxy_enabled proxy_protocol proxy_server"
+	for v in $ucivv; do
+		[ -z "$(config_get $1 $v)" ] && grep -qEv "^(download_url|rsync_url|proxy_protocol|proxy_server)$" <<< "$v" && {
+			>&2 echo "$(basename $0): section $1 option $v cannot be empty"
+			let error++
+		}
+		config_get GLOBAL_$v $1 $v
+	done
+
+	[ "$error" -gt 0 ] && return 1 || return 0
+}
+
+validate_section_config() {
+	uci_load_validate "$CONFIG_NAME" "$SCONFIG" "$1" "$2" \
+		'download_url:string' \
+		'rsync_url:string' \
+		'home_url:string' \
+		'bwlimit:uinteger:8000' \
+		'auto_exec:bool:1' \
+		'cron_expression:string' \
+		'proxy_enabled:bool:0' \
+		'proxy_protocol:string:socks5' \
+		'proxy_server:string'
+}
 
 validate_section_release() {
 	uci_load_validate $CONFIG_NAME $RELEASE "$1" "$2" \
@@ -51,10 +77,9 @@ validate_section_release() {
 		'name:uciname' \
 		'version:string' \
 		'target:string' \
-		'subtarget:string' \
-		'extra:bool:0' \
 		'pkgarch:string' \
-		'model:string'
+		'model:string' \
+		'extra:bool:0'
 }
 
 gen_order() {
@@ -67,10 +92,10 @@ gen_order() {
 	json_add_object
 	json_add_string name "$name"
 	json_add_string version "$version"
-	json_add_string target "$target/$subtarget"
-	json_add_boolean extra "$extra"
+	json_add_string target "$target"
 	json_add_string arch "$pkgarch"
 	json_add_string model "$model"
+	json_add_boolean extra "$extra"
 	json_close_object
 	orders="$(json_dump)"
 }
@@ -80,7 +105,9 @@ sync_instance() {
 
 	procd_open_instance 'sync'
 	procd_set_param command "$SYNCEXE" -o "$1"
-	procd_append_param command -l "$bwlimit" -d "$homepath" ${ALL_PROXY:+-x $ALL_PROXY}
+	procd_append_param command -l "$bwlimit" -d "$homepath" ${ALL_PROXY:+-x $ALL_PROXY} \
+		${GLOBAL_download_url:+--downloadurl "$GLOBAL_download_url"} \
+		${GLOBAL_rsync_url:+--rsyncurl "$GLOBAL_rsync_url"}
 	#procd_set_param respawn
 	#procd_set_param stdout 1
 	procd_set_param stderr 1
@@ -95,11 +122,14 @@ start_service() {
 	# mount point check
 	[ -n "$(df -hT|grep "$MNTPKGS")" ] || return 1
 
-	local homeurl homepath bwlimit
-	eval "homeurl=\$CONFIG_${CONFIG_SECTIONS%% *}_home_url"
-	[ -n "$homeurl" ] && homepath="/www/$homeurl" || homepath="$DEF_HOMEPATH"
+	validate_section_config "$SCONFIG" define_global || return $?
+	local homepath bwlimit
+	[ -n "$GLOBAL_home_url" ] && homepath="/www/$GLOBAL_home_url" || homepath="$DEF_HOMEPATH"
 	[ -d "$homepath" ] || { >&2 echo -e "$CONFIG_NAME: The Home Path '$homepath' is invalid. please check the 'home_url'"; return 1; }
-	eval "bwlimit=\$CONFIG_${CONFIG_SECTIONS%% *}_bwlimit"
+	bwlimit="$GLOBAL_bwlimit"
+	[ "$GLOBAL_proxy_enabled" = "1" ] && {
+		export ALL_PROXY=$GLOBAL_proxy_protocol://$GLOBAL_proxy_server
+	}
 
 	local orders='{ "orders": [] }'
 	config_foreach validate_section_release $RELEASE gen_order
@@ -124,8 +154,10 @@ start_service() {
 }
 
 getinfo() {
-local rawhtml stables releases targets pkgarchs
-rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$OPENWRT_URL")"
+validate_section_config "$SCONFIG" define_global
+local rawhtml stables releases targets pkgarchs download_url="${GLOBAL_download_url:-$DOWNLOAD_URL}"
+# Versions
+rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url")"
 stables="$( \
 echo "$rawhtml" | sed -n '/Stable Release/,/Development Snapshots/p' \
 | sed -n '/<ul>/,/<\/ul>/p' | grep 'OpenWrt' \
@@ -136,13 +168,25 @@ echo "$rawhtml" | sed -n '/Release Archive/,/\$/p' \
 | sed -n '/<ul>/,/<\/ul>/p' | grep 'OpenWrt' \
 | sed -E "s|.+\breleases/([\.0-9]+)/.+|\1|g" \
 )"
-rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$OPENWRT_URL/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_TARGETS")"
+# Targets
+rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_TARGETS")"
 targets="$( \
 echo "$rawhtml" \
 | sed -n '/<table>/,/<\/table>/p' | grep '<a href=' \
 | sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
 )"
-rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$OPENWRT_URL/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_PACKAGES")"
+## subTargets
+fulltargets="$( \
+for target in $targets; do
+	subtargets="$(curl -sL "$download_url/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_TARGETS/$target/" \
+		| sed -n '/<table>/,/<\/table>/p' | grep '<a href=' \
+		| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
+	)"
+	for subtarget in $subtargets; do sed "s|^|$target/|" <<< "$subtarget"; done
+done \
+)"
+# Archs
+rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_PACKAGES")"
 pkgarchs="$( \
 echo "$rawhtml" \
 | sed -n '/<table>/,/<\/table>/p' | grep '<a href=' \
@@ -154,23 +198,22 @@ echo -e "$stables\n$releases"
 echo -e "$stables\n$releases" > "$RELEASES_LIST"
 mkdir -p "${TARGETS_LIST%/*}" 2>/dev/null
 echo "Targets:"
-echo "$targets"
-echo "$targets" > "$TARGETS_LIST"
+echo "$fulltargets"
+echo "$fulltargets" > "$TARGETS_LIST"
 mkdir -p "${PKGARCHS_LIST%/*}" 2>/dev/null
 echo "PKGArchs:"
 echo "$pkgarchs"
 echo "$pkgarchs" > "$PKGARCHS_LIST"
 }
 
-gethomeurl() {
-home_url="$1" home_path=
-[ -z "$home_url" ] && home_url="$(uci -q get $CONFIG_NAME.@$TYPEDSECTION[0].home_url)"
+gethome() {
+home_url="${1:-$(uci -q get $CONFIG_NAME.$SCONFIG.home_url)}"
 home_url="${home_url:-$DEF_HOMEURL}"
 home_path="/www/$home_url"
 }
 
 checkln() {
-gethomeurl
+gethome
 
 # clean up old symlink
 ls -l /www|grep "\-> $MNTPKGS"|grep -v " $home_url -> $MNTPKGS"|sed -En "s,.+ ('.+'|\S+) -> ${MNTPKGS}$,'/www/\1',p" | xargs rm -f 
@@ -179,7 +222,7 @@ find /www/* ! -type l -maxdepth 0|sed "s|.*/||g"
 }
 
 symln() {
-gethomeurl "$1"
+gethome "$1"
 
 # make mount dir
 [ -e "$home_path" ] || { ln -s "$MNTPKGS" "$home_path" 2>/dev/null; ln -s "$RESULTPATH" "$home_path/results" 2>/dev/null; return 0; }
@@ -201,14 +244,14 @@ fi
 
 cleanup_regex() {
 	[ "$2" == "0" ] || { >&2 echo "section $1 validation failed"; return 1; }
-	targets="${targets:+$targets|}/$version/$URLHREF_VERS_TARGETS/$target/$subtarget\b"
+	targets="${targets:+$targets|}/$version/$URLHREF_VERS_TARGETS/$target\b"
 	packages="${packages:+$packages|}/$version/$URLHREF_VERS_PACKAGES\b"
 	pkgarchs="${pkgarchs:+$pkgarchs|}/$URLHREF_PACKAGES_PREFIX${version%\.*}/$pkgarch\b"
 }
 
 cleanup() {
 local autorm="$1"
-gethomeurl
+gethome
 
 local count targets packages pkgarchs
 [ -d "$home_path/$URLHREF_RELEASES" ] || return 1
@@ -217,12 +260,12 @@ config_foreach validate_section_release $RELEASE cleanup_regex || return $?
 
 #count=$(uci -q show $CONFIG_NAME|grep "=$RELEASE"|sed -E "s|.+@$RELEASE\[(\d+)\].+|\1|"|tail -n1)
 #
-#local ucivv="version target subtarget pkgarch"
+#local ucivv="version target pkgarch"
 #for i in $(seq 0 $count); do
 #	for _var in $ucivv; do
 #		eval "local $_var=\$(uci -q get $CONFIG_NAME.@$RELEASE[$i].$_var)"
 #	done
-#	targets="${targets:+$targets|}/$version/$URLHREF_VERS_TARGETS/$target/$subtarget\b"
+#	targets="${targets:+$targets|}/$version/$URLHREF_VERS_TARGETS/$target\b"
 #	packages="${packages:+$packages|}/$version/$URLHREF_VERS_PACKAGES\b"
 #	pkgarchs="${pkgarchs:+$pkgarchs|}/$URLHREF_PACKAGES_PREFIX${version%\.*}/$pkgarch\b"
 #done
@@ -246,4 +289,8 @@ restart() {
 boot() {
 	mkdir -p "$RESULTPATH" 2>/dev/null
     return 0
+}
+
+service_triggers() {
+      procd_add_reload_trigger "packagesync"
 }
diff --git a/kiddin9/master/openwrt-natmapt/files/natmap.init b/kiddin9/master/openwrt-natmapt/files/natmap.init
--- a/kiddin9/master/openwrt-natmapt/files/natmap.init
+++ b/kiddin9/master/openwrt-natmapt/files/natmap.init
@@ -74,7 +74,10 @@ define_global() {
 	local error=0
 	local v ucivv="enable def_tcp_stun def_udp_stun def_http_server def_fwmark_value def_tcp_interval def_udp_interval"
 	for v in $ucivv; do
-		[ -z "$(config_get $1 $v)" ] && err_msg__empty $1 $v && let error++
+		[ -z "$(config_get $1 $v)" ] && grep -qEv "^(def_fwmark_value)$" <<< "$v" && {
+			err_msg__empty $1 $v
+			let error++
+		}
 		config_get GLOBAL_$v $1 $v
 	done
 
@@ -288,8 +291,19 @@ natmap_instance() {
 }
 
 clear_status_files() {
+	local f sid="$1"
+
 	mkdir -p "${STATUS_PATH}" 2>/dev/null
-	find "${STATUS_PATH}" -type f -print0 | xargs -0 rm -f --
+	pushd "${STATUS_PATH}" >/dev/null
+	if [ -n "$sid" ]; then
+		for f in *.json; do
+			[ "$(jsonfilter -q -i $f -e '@.sid')" = "$sid" ] || continue
+			rm -f $f; break
+		done
+	else
+		find * -type f -print0 | xargs -0 rm -f --
+	fi
+	popd >/dev/null
 }
 
 # err_msg__empty <section> <option>
@@ -302,11 +316,13 @@ launcher() {
 	[ "$enable" = 0 ] && return 0
 
 	# global options
-	[ "$udp_mode" = 1 ] \
-		&& echo ${stun_server:=$GLOBAL_def_udp_stun} ${interval:=$GLOBAL_def_udp_interval} >/dev/null \
-		|| echo ${stun_server:=$GLOBAL_def_tcp_stun} ${interval:=$GLOBAL_def_tcp_interval} >/dev/null
-	echo ${http_server:=$GLOBAL_def_http_server} >/dev/null
-	echo ${fwmark_value:=$GLOBAL_def_fwmark_value} >/dev/null
+	if [ "$udp_mode" = 1 ]; then
+		local stun_server=${stun_server:-$GLOBAL_def_udp_stun} interval=${interval:-$GLOBAL_def_udp_interval}
+	else
+		local stun_server=${stun_server:-$GLOBAL_def_tcp_stun} interval=${interval:-$GLOBAL_def_tcp_interval}
+	fi
+	local http_server=${http_server:-$GLOBAL_def_http_server}
+	local fwmark_value=${fwmark_value:-$GLOBAL_def_fwmark_value}
 	# natmap options
 	local error=0
 	local proto ifname bind_ip lan_addr
@@ -315,7 +331,8 @@ launcher() {
 		ipv4) network_get_device ifname "$DEF_WAN";;
 		ipv6) network_get_device ifname "$DEF_WAN6";;
 	esac
-	[ -z "${bind_ifname:=$ifname}" ] && >&2 echo "$(basename $0): section $1 option bind_ifname parsing failed, there may be no $family network connection" && let error++
+	local bind_ifname=${bind_ifname:-$ifname}
+	[ -z "$bind_ifname" ] && >&2 echo "$(basename $0): section $1 option bind_ifname parsing failed, there may be no $family network connection" && let error++
 	case "$family" in
 		ipv4)
 			eval "bind_ip=\"\${NIC_${bind_ifname//[[:punct:]]/_}%/*}\""
@@ -363,7 +380,7 @@ launcher() {
 		[ -x "$ddns_script" ] || { >&2 echo "$(basename $0): section $1 option ddns_script '$ddns_script' is empty or non-executable"; let error++; }
 		if [ -n "$ddns_srv" ]; then
 			[ -z "$ddns_srv_serv" ] && err_msg__empty $1 ddns_srv_serv && let error++
-			echo ${ddns_srv_target:=$ddns_srv} >/dev/null
+			local ddns_srv_target=${ddns_srv_target:-$ddns_srv}
 		fi
 	fi
 
@@ -410,6 +427,7 @@ start_service() {
 	[ "${GLOBAL_enable:=0}" == "0" ] && return 1
 
 	if [ -n "$sid" ]; then
+		clear_status_files "$sid"
 		validate_section_natmap "$sid" launcher
 	else
 		clear_status_files
@@ -417,14 +435,16 @@ start_service() {
 	fi
 }
 
+stop_service() {
+	local sid="$1"
+	clear_status_files "$sid"
+}
+
 reload_service() {
-	stop
-	start
+	stop "$@"
+	start "$@"
 }
 
 service_started() { procd_set_config_changed firewall; }
 
-service_stopped() {
-	clear_status_files
-	procd_set_config_changed firewall
-}
+service_stopped() { procd_set_config_changed firewall; }
