2024.04.27 5:39

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -97,6 +97,11 @@ jobs:
         fi
 
         git pull --rebase origin master
+        if [ $? -ne 0 ]; then
+            echo "Rebase failed, please resolve conflicts manually!"
+            exit 1
+        fi
+        
         git push git@github.com:lysgwl/openwrt-package.git HEAD:master 
 
     #- name: Push changes repository
