Delete the disputed repository because Repository unavailable due to DMCA takedown

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -74,50 +74,50 @@ jobs:
         source ${scripts_file}
         clone_remote_repo 1 ${package_path_rel}
         
-    - name: Get coolsnowwolf repository contents
-      if: env.REPO_LEDE_COND != 0 && !cancelled()
-      run: |
-        package_path_rel="$PWD/coolsnowwolf"
-        mkdir -p "$package_path_rel"
+    #- name: Get coolsnowwolf repository contents
+    #  if: env.REPO_LEDE_COND != 0 && !cancelled()
+    #  run: |
+    #    package_path_rel="$PWD/coolsnowwolf"
+    #    mkdir -p "$package_path_rel"
+    #    
+    #    scripts_file=${{ env.scripts }}
+    #    if [ ! -x "${scripts_file}" ]; then
+    #        echo "the script cannot be executed, please check!"
+    #        exit 1
+    #    fi
+    #    
+    #    source ${scripts_file} 
+    #    #get_remote_repo 1 ${package_path_rel}
         
-        scripts_file=${{ env.scripts }}
-        if [ ! -x "${scripts_file}" ]; then
-            echo "the script cannot be executed, please check!"
-            exit 1
-        fi
+    #- name: Get shidahuilang repository contents
+    #  if: env.REPO_SDHL_COND != 0 && !cancelled()
+    #  run: |
+    #    package_path_rel="$PWD/shidahuilang"
+    #    mkdir -p "$package_path_rel"
+    #    
+    #    scripts_file=${{ env.scripts }}
+    #    if [ ! -x "${scripts_file}" ]; then
+    #        echo "the script cannot be executed, please check!"
+    #        exit 1
+    #    fi
+    #    
+    #    source ${scripts_file}
+    #    #get_remote_repo 3 ${package_path_rel}
         
-        source ${scripts_file} 
-        get_remote_repo 1 ${package_path_rel}
-        
-    - name: Get shidahuilang repository contents
-      if: env.REPO_SDHL_COND != 0 && !cancelled()
-      run: |
-        package_path_rel="$PWD/shidahuilang"
-        mkdir -p "$package_path_rel"
-        
-        scripts_file=${{ env.scripts }}
-        if [ ! -x "${scripts_file}" ]; then
-            echo "the script cannot be executed, please check!"
-            exit 1
-        fi
-        
-        source ${scripts_file}
-        get_remote_repo 3 ${package_path_rel}
-        
-    - name: Get kiddin9 repository contents
-      if: env.REPO_KDDN_COND != 0 && !cancelled()
-      run: |
-        package_path_rel="$PWD/kiddin9"
-        mkdir -p "$package_path_rel"
-        
-        scripts_file=${{ env.scripts }}
-        if [ ! -x "${scripts_file}" ]; then
-            echo "the script cannot be executed, please check!"
-            exit 1
-        fi
-        
-        source ${scripts_file}
-        get_remote_repo 4 ${package_path_rel}    
+    #- name: Get kiddin9 repository contents
+    #  if: env.REPO_KDDN_COND != 0 && !cancelled()
+    #  run: |
+    #    package_path_rel="$PWD/kiddin9"
+    #    mkdir -p "$package_path_rel"
+    #    
+    #    scripts_file=${{ env.scripts }}
+    #    if [ ! -x "${scripts_file}" ]; then
+    #        echo "the script cannot be executed, please check!"
+    #        exit 1
+    #    fi
+    #    
+    #    source ${scripts_file}
+    #    #get_remote_repo 4 ${package_path_rel}    
         
     - name: Commit and push repository using SSH
       run: |
