2024.05.13 09:55

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -16,8 +16,8 @@ on:
 env:
   BUILD_SCRIPT: run-scripts.sh
   REPO_OTHER_COND: 1
-  REPO_LEDE_COND:  1
-  REPO_SDHL_COND:  1
+  REPO_LEDE_COND:  0
+  REPO_SDHL_COND:  0
   
 jobs:
   build:   # update build repo-sync
@@ -71,8 +71,6 @@ jobs:
         source ${scripts_file}
         clone_remote_repo ${REPO_OTHER_COND} ${package_path_rel}
         
-        check_git_commit ${package_path_rel}
-        
     - name: Get coolsnowwolf repository contents
       if: env.REPO_LEDE_COND != 0 && !cancelled()
       run: |
@@ -87,8 +85,6 @@ jobs:
         
         source ${scripts_file} 
         get_remote_repo ${REPO_LEDE_COND} ${package_path_rel}
-        
-        check_git_commit ${package_path_rel}
         
     - name: Get shidahuilang repository contents
       if: env.REPO_SDHL_COND != 0 && !cancelled()
@@ -105,20 +101,18 @@ jobs:
         source ${scripts_file}
         get_remote_repo 3 ${package_path_rel} "Official"
         
-        check_git_commit ${package_path_rel}
+    - name: Commit and push repository using SSH
+      run: |
+        package_path_rel="$PWD"
         
-    #- name: Commit and push repository using SSH
-    #  run: |
-    #    package_path_rel="$PWD"
-    #    
-    #    scripts_file=${{ env.scripts }}
-    #    if [ ! -x "${scripts_file}" ]; then
-    #        echo "the script cannot be executed, please check!"
-    #        exit 1
-    #    fi
-    #
-    #    source ${scripts_file}
-    #    check_git_commit ${package_path_rel}    
+        scripts_file=${{ env.scripts }}
+        if [ ! -x "${scripts_file}" ]; then
+            echo "the script cannot be executed, please check!"
+            exit 1
+        fi
+    
+        source ${scripts_file}
+        check_git_commit ${package_path_rel}    
 
     #- name: Push changes repository
     #  uses: ad-m/github-push-action@master
