2024.05.02 12:29

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -181,6 +181,12 @@ jobs:
                 local entry=$1
                 local field=$2
                 
+                # 检查entry是否为有效的JSON对象
+                if ! echo "$entry" | jq -e . >/dev/null 2>&1; then
+                    echo "Error: entry is not a valid JSON object."
+                    return
+                fi
+                
                 # 检查字段 
                 if ! echo "$entry" | jq -e ". | has(\"$field\")" >/dev/null; then
                     echo "Field($field) parsing error, please check!"
@@ -190,7 +196,7 @@ jobs:
                 # 获取字段值
                 value=$(echo "$entry" | jq -r ".$field")
                 if [ -z "$value" ]; then
-                    echo "The parsing field($field) is empty, please check"
+                    echo "The parsing field($field) is empty, please check!"
                     return
                 fi
  
