2024.05.07 15:16

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -15,7 +15,7 @@ on:
 env:
   BUILD_SCRIPT: run-scripts.sh
   REPO_OTHER_COND: 1
-  REPO_LEDE_COND:  0 
+  REPO_LEDE_COND:  1
   REPO_SDHL_COND:  0
   
 jobs:
@@ -77,10 +77,15 @@ jobs:
         mkdir -p "$package_path_rel"
         
         scripts_file=${{ env.scripts }}
-        if [ -x "${scripts_file}" ]; then
-            source ${scripts_file} 
-            get_remote_repo ${REPO_LEDE_COND} ${package_path_rel}
+        if [ ! -x "${scripts_file}" ]; then
+            echo "the script cannot be executed, please check!"
+            exit 1
         fi
+        
+        source ${scripts_file} 
+        get_remote_repo ${REPO_LEDE_COND} ${package_path_rel}
+        
+        check_git_commit ${package_path_rel}
         
     - name: Get shidahuilang repository contents
       if: env.REPO_SDHL_COND != 0 && !cancelled()
