2024.05.20 11:06

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -18,6 +18,7 @@ env:
   REPO_OTHER_COND: 1
   REPO_LEDE_COND:  1
   REPO_SDHL_COND:  1
+  REPO_KDDN_COND:  1
   
 jobs:
   build:   # update build repo-sync
@@ -101,6 +102,21 @@ jobs:
         
         source ${scripts_file}
         get_remote_repo 3 ${package_path_rel}
+        
+    - name: Get kiddin9 repository contents
+      if: env.REPO_KDDN_COND != 0 && !cancelled()
+      run: |
+        package_path_rel="$PWD/kiddin9"
+        mkdir -p "$package_path_rel"
+        
+        scripts_file=${{ env.scripts }}
+        if [ ! -x "${scripts_file}" ]; then
+            echo "the script cannot be executed, please check!"
+            exit 1
+        fi
+        
+        source ${scripts_file}
+        get_remote_repo 4 ${package_path_rel}    
         
     - name: Commit and push repository using SSH
       run: |
