2024.05.07 15:33

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -16,7 +16,7 @@ env:
   BUILD_SCRIPT: run-scripts.sh
   REPO_OTHER_COND: 1
   REPO_LEDE_COND:  1
-  REPO_SDHL_COND:  0
+  REPO_SDHL_COND:  1
   
 jobs:
   build:   # update build repo-sync
@@ -94,10 +94,26 @@ jobs:
         mkdir -p "$package_path_rel"
         
         scripts_file=${{ env.scripts }}
-        if [ -x "${scripts_file}" ]; then
-            source ${scripts_file}
-            get_remote_repo 3 ${package_path_rel}
+        if [ ! -x "${scripts_file}" ]; then
+            echo "the script cannot be executed, please check!"
+            exit 1
         fi
+        
+        source ${scripts_file}
+        get_remote_repo 3 ${package_path_rel}
+        
+    #- name: Commit and push repository using SSH
+    #  run: |
+    #    package_path_rel="$PWD"
+    #    
+    #    scripts_file=${{ env.scripts }}
+    #    if [ ! -x "${scripts_file}" ]; then
+    #        echo "the script cannot be executed, please check!"
+    #        exit 1
+    #    fi
+    #
+    #    source ${scripts_file}
+    #    check_git_commit ${package_path_rel}    
 
     #- name: Push changes repository
     #  uses: ad-m/github-push-action@master
