2024.04.29 14:20

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -119,23 +119,37 @@ jobs:
             git add .
             git commit -a -m "Merge code repository on $current_date"
             
-            echo "Changes committed. Proceeding with pull and push."
-            git fetch origin master
-            
-            STATUS=$?
-            if [ $STATUS -ne 0 ]; then
-                echo "Fetch failed, please check your remote and network."; exit 1
+            commit_status=$?
+            if [ $commit_status -ne 0 ]; then
+                echo "Nothing to commit, working tree clean"
+                echo "Checking if local branch is ahead of remote branch..."
+                
+                ahead=$(git status | grep 'Your branch is ahead' | wc -l)
+                if [ $ahead -eq 0 ]; then
+                    echo "Local branch is not ahead; no need to push."
+                else
+                    echo "Local branch is ahead of remote, pushing changes..."
+                    git push git@github.com:lysgwl/openwrt-package.git HEAD:master
+                fi
             else
-                git merge FETCH_HEAD
-            fi
-            
-            # 检测是否存在冲突
-            if git ls-files -u | grep -q '^'; then
-                echo "Merge conflicts detected. Please resolve them manually."
-                exit 1
-            fi
-            
-            git push git@github.com:lysgwl/openwrt-package.git HEAD:master 
+                echo "Changes committed. Proceeding with pull and push."
+                git fetch origin master
+                
+                STATUS=$?
+                if [ $STATUS -ne 0 ]; then
+                    echo "Fetch failed, please check your remote and network."; exit 1
+                else
+                    git merge FETCH_HEAD
+                    
+                    # 检测是否存在冲突
+                    if git ls-files -u | grep -q '^'; then
+                        echo "Merge conflicts detected. Please resolve them manually."
+                        exit 1
+                    fi
+                    
+                    git push git@github.com:lysgwl/openwrt-package.git HEAD:master
+                fi
+            fi 
         fi
 
     #- name: Push changes repository
