2024.05.07 13:24

diff --git a/.github/workflows/update_other_package_repo.yml b/.github/workflows/update_other_package_repo.yml
--- a/.github/workflows/update_other_package_repo.yml
+++ b/.github/workflows/update_other_package_repo.yml
@@ -15,8 +15,8 @@ on:
 env:
   BUILD_SCRIPT: run-scripts.sh
   REPO_OTHER_COND: 1
-  REPO_LEDE_COND:  1
-  REPO_SDHL_COND:  1
+  REPO_LEDE_COND:  0 
+  REPO_SDHL_COND:  0
   
 jobs:
   build:   # update build repo-sync
@@ -35,14 +35,12 @@ jobs:
       run: |
         scripts_file="${GITHUB_WORKSPACE}/.github/scripts/${BUILD_SCRIPT}"
         if [ ! -e "${scripts_file}" ]; then
+            echo "the script does not exist, please check!"
             exit 1
         fi
 
         chmod +x "${scripts_file}"
         echo "scripts=${scripts_file}" >> $GITHUB_ENV
-        
-        source ${scripts_file}
-        update_linux_env
 
     - name: Set SSH key and known_hosts
       uses: webfactory/ssh-agent@v0.9.0   # appleboy/ssh-action@master
@@ -62,10 +60,15 @@ jobs:
         mkdir -p "$package_path_rel"
         
         scripts_file=${{ env.scripts }}
-        if [ -x "${scripts_file}" ]; then
-            source ${scripts_file}
-            clone_remote_repo ${REPO_OTHER_COND} ${package_path_rel}
-        fi        
+        if [ ! -x "${scripts_file}" ]; then
+            echo "the script cannot be executed, please check!"
+            exit 1
+        fi
+        
+        source ${scripts_file}
+        clone_remote_repo ${REPO_OTHER_COND} ${package_path_rel}
+        
+        check_git_commit ${package_path_rel}
         
     - name: Get coolsnowwolf repository contents
       if: env.REPO_LEDE_COND != 0 && !cancelled()
@@ -91,16 +94,6 @@ jobs:
             get_remote_repo 3 ${package_path_rel}
         fi
 
-    - name: Commit and push repository using SSH
-      run: |
-        package_path_rel="$PWD"
-        
-        scripts_file=${{ env.scripts }}
-        if [ -x "${scripts_file}" ]; then
-            source ${scripts_file}
-            check_git_commit ${package_path_rel}
-        fi
-        
     #- name: Push changes repository
     #  uses: ad-m/github-push-action@master
     #  with:
